### ISSUE TITLE
Compatibility problem with Formidable Pro

### ISSUE THREAD

**Issue by dendeffe** [CarlosRios/sortable-posts#5]
Hi,

I am having problems getting the dragging to work when Formidable Pro is active. Haven’t been able to figure out what is happening.

http://take.ms/y00ky

https://formidablepro.com/

**Comment by CarlosRios** [comment]
Hi @dendeffe,

Looks like it might be a javascript conflict based on that screencast. Can you show me whats going on in your browser's inspector? Unfortunately I don't have formidable pro purchased and won't be able to replicate the error.

**Comment by dendeffe** [comment]
Hi @CarlosRios,

I’m afraid my console is empty, even when I start dragging: http://take.ms/nxIfj

I’ll do some more debugging when I get more time.
For reference, you can also generate the problem with the free version of Formidable Forms:  https://wordpress.org/plugins/formidable/

**Comment by dendeffe** [comment]
Haven’t gotten very far on this, but your start for jQuery UI sortable simply doesn’t seem to fire with Formidable Pro enabled. 

https://github.com/CarlosRios/sortable-posts/blob/master/assets/js/sortable-posts.js#L25

Formidable Pro does use JQuery UI as well.

**Comment by CarlosRios** [comment]
@dendeffe I figured that was the reason. I'm enqueuing the JQuery Ui sortable plugin that comes with WordPress. I'm not sure if Formidable Pro is using that or another version. I'll take a look at their plugin to see what the conflict is because their could be a possible conflict with other plugins that are using the same script.

**Comment by CarlosRios** [comment]
@dendeffe I think I figured it out. Turns out the class I'm adding to the body 'sortable-posts' was being attached to the class that Formidable forms was adding to the body as well. That class is what the JS uses to determine elements to make sortable in the DOM, so that should do it.

https://github.com/CarlosRios/sortable-posts/commit/e2378db2ae13552f0d4059b34bbefb51d91f1110

**Comment by dendeffe** [comment]
Yes, that works. Thanks for following up on this.

**Comment by CarlosRios** [comment]
No problem :) Please feel free to contribute to the plugin as you please. Also, if you could leave a positive review on Wordpress.org that would help me a ton!
